### ISSUE TITLE
Improve DB error handling

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#207]

**Comment by simerplaha** [comment]
# Checkpoint documentation

Switched worked on higher priority tasks. Noted the following list of things TODO so far. Will continue after resolving higher priority tasks.

- Are logs being logged to a file? Since there is no file appender in `logback.xml`, I’m assuming logs are piped into a file?
- Are transactions that are rollbacked logged?
- Check that when application starts up and a query is executed, that failed queries are logged.
- How much is sync logging? Are sync’s logging to the same file?
- Are failed web requests logged?
- Is query timeout logged?
- Check that logs are not unnecessarily overflowed.

**Comment by polarker** [comment]
Here is the rollback configuration for full node: https://github.com/alephium/alephium/blob/master/flow/src/main/resources/logback.xml
