### ISSUE TITLE
Endpoint to get address' transasactions by time range

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#375]
This could be useful for the front end to implement this https://github.com/alephium/explorer/issues/41
We need to be careful when choosing the max time range, a big one could be costly for addresses with lots of transactions

we already have the `/addresses/<address>/transactions` , we  could have `/addresses/<address>/timeranged-transactions?fromTs=x&toTs=x`

**Comment by tdroxler** [comment]
probably we won't be able to use a full year, as it could take too long to return a query for the big addresses.
Is it fine to loop on your side to get all the data you want?

**Comment by mvaivre** [comment]
I fear that this might get a bit messy... 
Also, the "full year" is probably the most interesting option for task purposes.

Have you made some benchmark tests, to check how long it takes to extract a full year worth of TXs for an address?

**Comment by tdroxler** [comment]
>Have you made some benchmark tests, to check how long it takes to extract a full year worth of TXs for an address?

Not yet, but will do as soon as the feature is there!

**Comment by simerplaha** [comment]
To get a sense of how long it takes to extract "a full years worth of TXs", here are some benchmarks of the query specific to PR. 

We get 
- 13.2 queries/second for reading an address with 50,000 transactions
- 1.1 queries/second for reading an address with 500,000 transactions
- Generated data
  - Address count: 1
  - A unique `block_timestamp` was generated per 5 transactions (so 5 transactions per address per block).
      - So 10,000 unique `block_timestamp`s for first benchmark
      -  And 100,000 unique `block_timestamp`s for second benchmark
  - With HikariCP disabled 
 
Obviously as more addresses get added to the table the performance will decrease. For example: With 100 address the above performance of 13.2 queries/second reduces to 9 queries/second.

I might be wrong here but "a full years worth of TXs" is a bit subjective right? Because in theory an address could have millions transactions over a period of month or only 1 transaction over a period of couple of years. So adding restriction on time period range might not address the concern of fetching too much data?

Maybe we want to limit the maximum number of transactions returning instead of time-period using `Pagination`? 

For example: If we want to limit to a max of `100,000` transactions per request, UI could dispatch a request for `100,000 + 1` with the requested time-period range. If the response has `100,000 + 1` transactions, another request could be dispatched to fetching the remaining using pagination and if the response contains less than `100,000` transactions that completes the request?

#### Benchmark screenshots

![image](https://user-images.githubusercontent.com/1773953/199161313-5e50da16-9bb3-44e0-8825-dfdc0d66fd1a.png)

![image](https://user-images.githubusercontent.com/1773953/199161371-7fbc6780-6a42-40fe-ac8b-e09c6dd48d06.png)

![image](https://user-images.githubusercontent.com/1773953/199161392-2efd1610-84db-4069-8b9c-9511b0862676.png)

**Comment by mvaivre** [comment]
Thanks a lot @simerplaha, that's a very valuable input!

I suggest we split the implementation into multiple steps; we start as simple as possible, we monitor, and finally we "complexify" the implementation a bit if there's a clear need from the community.

1) We offer the TXs export with the time ranges shown above, but with a max of `100k` transactions. Above `100k` TXs the export is simply impossible (ie. an error is shown before the request is executed). 
*Question: can we efficiently query how many TXs would be fetched before actually fetching them?*

2) We monitor how many calls failed because `nb. TX > 100k`. If possible, it would be awesome to collect metrics on how many TXs our users tried to fetch (avg., std dev etc.). Based on this data, we may bump the max limit to say, `200k`.

3) If there's a strong need for exporting even more TXs, we implement the pagination system you described, with multiple chained requests. 

What do you think? Would it make sense?

Thanks again!

**Comment by tdroxler** [comment]
1.
> can we efficiently query how many TXs would be fetched before actually fetching them?

yes we can, as we first fetch all tx_hashs and then use them to grab all details of each tx, so we could stop after the step of getting tx_hashes.

2. mmm monitoring might be a bit complicated, but what I could do is to first run a manual query to count how many txs there are per address, this could give us a good feeling on the right number.

3. yep we could add pagination latter.

**Comment by tdroxler** [comment]
here are the top 15 addresses with their number of txs:

```
 1Gzp3Wc42fanrbAqknYmSaZLfC567bP3JWprDCiuJ8rbP | 1156781
 19WzSnmNC1SQ6v7RpFFXhpcMcFSiwM4nKTSdbwgSJfSHy | 1069618
 14kSoi8pFMn2wMJFZJgGpFSA7GyNMtwWKnsKc1KidZ8Bu | 1069184
 12jK2jHyyJTJyuRMRya7QJSojgVnb5yh4HVzNNw6BTBDF | 1068683
 1BU6eg4bnn4gFgpSx6U96xqwZxyJHwEdMajCE3wminc3e | 437087
 134RbnQXBWFCnR4HhmEgFjkotkdmNzNeYqhQ84ZKjHnjN | 341285
 1DKWCEc9HjhchKoMCMA4J1nbNGNjrAoPFnkcgA1w6h7jh | 341241
 134dmgh9AZNimp9ZAYpWBTwv3ddouETBTyq6134mBvVk2 | 340835
 12WhBVry3PXzTyCm389eSZMVsDSQZjGh5csv6CPrNfgtz | 340681
 17R6Ptkz9i1LhiKyMhnitUMkgFygGeeQUFZvRx6GgV8Fc | 279388
 1AYR6H9LqCUN6BsRCQg2eiHHUYZ6hBbvyRz2AYzda1YVa | 87142
 13vPxxvdLG5Z9pmzbeb7xLbxpqX8HN7hT3WbyE36eqMeV | 63520
 1EW4DKjCvXWEbipBNFxf1N3UDhdYmqX7NBmjjizvd9j74 | 62543
 19nnsAodfSnrnVmmPrHN3ZaycHFz4NSgMmmW9YG3TEdGx | 57379
 163CahfVB61xn9pY8dvFLznETGzCopPTwFTvHqmno3Fq6 | 57280
```

**Comment by polarker** [comment]
@tdroxler @simerplaha We could add indexes for these special addresses to improve query performance. Could you please benchmark it?

**Comment by simerplaha** [comment]
Just to be clear, you mean indexes like the following?

```sql
create index address_1_idx on transaction_per_addresses (address) where address = '1Gzp3Wc42fanrbAqknYmSaZLfC567bP3JWprDCiuJ8rbP';
create index address_1_idx on transaction_per_addresses (address) where address = '19WzSnmNC1SQ6v7RpFFXhpcMcFSiwM4nKTSdbwgSJfSHy';
...
```

**Comment by tdroxler** [comment]
mmm that's sound a bit weird to create hardcode the addresses, also if suddenly those miners stop.  We will have indexes that won't be used anymore.

**Comment by simerplaha** [comment]
It is a bit odd. That's why I wanted to confirm.

> We could add indexes for these special addresses

I'm not sure what this mean. 

Let me know and I will run the asked benchmarks.

**Comment by polarker** [comment]
@tdroxler @simerplaha Yes, that's what I meant, to hardcode a list of special addresses for slow queries. It's just an idea that needs benchmark.

I know it's ugly... but it's probably the only way for the cases that a general optimization is not enough.

If the idea helps, we could have a service that regularly update and build indexes for those special addresses.

**Comment by polarker** [comment]
As always, no need to over-optimize of course If the current performance is enough.

**Comment by polarker** [comment]
Pseudo code:
```
def updateIndexesForHotAddresses(): Unit {
  val oldHotAddresses = getCurrentHotAddresses()
  val newHotAddresses = database.getHotAddresses()
  val (toRemove, toIndex) = diff(newHotAddresses, oldHotAddresses)
  removeIndexes(toRemove)
  addIndexes(toIndex)
}
```

**Comment by mvaivre** [comment]
As a side note, starting by limiting the export to `nb. TX < 100k` would restrict only 10 addresses from using the feature.
Also, some of those addresses probably belong to Gate, which doesn't need such a tool.
Such a limitation would still allow us to serve the large majority of our community (>95%?) so that may be an acceptable solution to start with? :)

**Comment by polarker** [comment]
I echo @mvaivre 's note. Owners of those hot addresses should be able to derive transaction history by themselves.

As counting nb.TX is pretty heavy, we may still want to have a service remember and update the list of hot addresses.

**Comment by simerplaha** [comment]
Discussed with Thomas. Closing as resolved by #378. Please reopen if needed.

**Comment by polarker** [comment]
@simerplaha @tdroxler Can we get an update on the final design of this feature? Thanks!

**Comment by tdroxler** [comment]
Sorry, a lot happen since 12 days and I totally forgot to update the issue.

I had some good progress for the export of txs through streaming, so we decided with Mika to wait for that to add the export in the wallet, to avoid adding to much logic in the front-end.

Now this endpoint, while the first idea was to target the export, is actually useful for an old idea in the wallet: to be able to fine-grain-search a tx by timestamp. It's a useful tool in any e-banking when you need to find back a tx that you know happen around a given date. Currently you would need to binary search on the page number to find back the right date. I'll create the corresponding issue in the explorer FE repo.
So we decided to merge the PR anyway even if it's not for the export.

Regarding the `HotAddressesServices`, this seems indeed a bit over-optimized for now, as the explorer is quite smooth even for addresses with  > 1M txs. But that's definitively something to keep in mind as we know psql can be slow for counting/sorting, I'll create a task so we don't forget.

Sorry again, it was definitively not the goal to ignore your inputs.

**Comment by tdroxler** [comment]
@polarker streaming is now implemented and seems pretty smooth as we limited to 10K txs, can we close this issue?

**Comment by polarker** [comment]
@tdroxler Yes, please! Thanks for the ping.
