### ISSUE TITLE
Support ALPH and token holder rank list

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#85]

**Comment by tdroxler** [comment]
@polarker do we still want this or we want to redirect to https://alph-top.web.app/ ?

**Comment by polarker** [comment]
Still low priority IMO, especially since there is a service available.

**Comment by tdroxler** [comment]
Discussed with the front-end team, we don't want to add such feature in the near/medium future, we don't think it's our role as the core team to "put in front" some given addresses, our explorer should stay partial, especially since there is a community driven project.
I will close the issue for now, it could be re-open latter if we change our mind.
